# Generated by Django 4.0 on 2022-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
        ),
    ]
